export const routes=[
    {
        name:'teammates',
        path:'/teammates'
    },
    {
        name:'Companies',
        path:'/companies'
    },
    {
        name:'Projects',
        path:'/projects'
    },
    {
        name:'Roles',
        path:'/roles'
    },
    {
        name:'Forms',
        path:'/forms'
    }
]